name: Ubuntu20.04, ROS2 Continuous Integration

on:
  push:
    branches:
    - master
    - devel
    - mnaveau/ubuntu20.04_ros1_ros2
  pull_request:
    branches:
    - master
    - devel

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      #
      # Setup the machines and build environment
      #
      - name: Install ROS.
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy

      #
      # Checkout the current branch
      #
      - uses: actions/checkout@v2

      #
      # Clone the dependencies in the ROS workspace
      #
      - name: Clone dependencies in the current workspace.
        shell: bash
        run: |
          ws_path = /home/runner/work/dynamic_graph_bridge/colcon_workspace
          mkdir -p $ws_path/src
          cd $ws_path/src
          git clone -b devel --single-branch --recursive https://github.com/stack-of-tasks/dynamic_graph_bridge_msgs.git
          
      #
      # Build dep and checkout from source.
      #
      - name: Build packages.
          ln -s /home/runner/work/dynamic_graph_bridge/dynamic_graph_bridge .
          colcon build

      #
      # Test the checkout package
      #
          colcon test --packages-select dynamic_graph_bridge --event-handlers console_direct+ --return-code-on-test-failure
